version: 1.0.{build}
environment:
    APPVEYOR_BLOCK_DOTNETCORE_TESTS_AUTORUN: false
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2017
configuration: Debug
platform:
- x64
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: SigfolioWallet.sln
  parallel: true
  verbosity: minimal
deploy: off
test_script:
 - cmd: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover ./SigfolioWallet.Test/ --test-adapter-path:. --logger:Appveyor
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "./SigfolioWallet.Test/coverage.opencover.xml" -t 5e9a3a7e-b0e7-492e-bac9-43401e17cbe5